name: Renovate

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"

permissions: {}

jobs:
  renovate:
    permissions:
      contents: read
    uses: projectbluefin/actions/.github/workflows/reusable-renovate.yml@4f6c41ff0a16a224f5e54ae80d7affbe2409b3d0 # v1
    secrets:
      renovate_token: ${{ secrets.RENOVATE_TOKEN }}
