name: Renovate

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"

permissions: {}

jobs:
  renovate:
    permissions:
      contents: read
    uses: projectbluefin/actions/.github/workflows/reusable-renovate.yml@ce1d0c6bb5baf8bab3a5b226e693c9fd26b3c4a8 # v1
    secrets:
      renovate_token: ${{ secrets.RENOVATE_TOKEN }}
