name: Validate Renovate Config

on:
  pull_request:
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"
      - ".github/workflows/validate-renovate.yml"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json"
      - ".github/workflows/renovate.yml"
      - ".github/workflows/validate-renovate.yml"

permissions:
  {}

jobs:
  validate:
    permissions:
      contents: read
    uses: projectbluefin/actions/.github/workflows/reusable-validate-renovate.yml@837850b6100b22c7920476035e7e1c28fdbba67f # v1
